#!/bin/bash

echo "//go:build cgo" > rflags.go
echo "//Code generated by genflags.sh; DO NOT EDIT." >> rflags.go
echo "package main" >> rflags.go

echo  >> rflags.go

touch dummy.c
dirty_cflags=($(MAKEFLAGS=-s R CMD COMPILE CC=echo dummy.c))
cflags=()
for value in "${dirty_cflags[@]}"; do
    [[ $value != "-c" ]] && \
    [[ $value != "dummy.c" ]] && \
    [[ $value != "-o" ]] && \
    [[ $value != "dummy.o" ]] && \
        cflags+=("$value")
done
rm dummy.c
echo "// #cgo CFLAGS: ${cflags[@]}" >> rflags.go

echo "// #cgo LDFLAGS: $(R CMD config --ldflags)" >> rflags.go
echo "import \"C\"" >> rflags.go

echo  >> rflags.go