//go:build cgo
//Code generated by genflags.sh; DO NOT EDIT.
package main

// #cgo CFLAGS: -I/stor/system/opt/R/R-3.6.1/lib/R/include -DNDEBUG -I/usr/local/include -fpic -g -O2
// #cgo LDFLAGS: -Wl,--export-dynamic -fopenmp -L/usr/local/lib -L/stor/system/opt/R/R-3.6.1/lib/R/lib -lR -lpcre -llzma -lbz2 -lz -lrt -ldl -lm -licuuc -licui18n
import "C"

